#!/usr/bin/env python3
"""
Quick fix suggestions for the OpenSky API no aircraft issue.
"""

print("QUICK FIX OPTIONS FOR NO AIRCRAFT ISSUE")
print("=" * 60)
print()
print("The issue: All aircraft are outside your 50km search radius")
print("Time: ~2:50 AM local time (very quiet time for air traffic)")
print()
print("IMMEDIATE SOLUTIONS:")
print()
print("1. UPDATE YOUR .env FILE:")
print("   Change SEARCH_RADIUS_KM=50 to SEARCH_RADIUS_KM=100")
print("   This will capture the aircraft that are 53-105km away")
print()
print("2. TEMPORARILY USE MOCK DATA:")
print("   In backend/api/opensky_client.py, line 240:")
print("   Change: USE_MOCK_DATA = False")
print("   To:     USE_MOCK_DATA = True")
print()
print("3. WAIT FOR BUSIER TIME:")
print("   Air traffic is much busier during:")
print("   - Morning: 6 AM - 10 AM")
print("   - Evening: 4 PM - 8 PM")
print()
print("PERMANENT SOLUTION:")
print()
print("Implement dynamic radius expansion (see patch_dynamic_radius.py)")
print("This will automatically increase the search radius when no aircraft")
print("are found in the initial radius.")
print()
print("CURRENT NEAREST AIRCRAFT:")
print("- MNB213 (Turkish): 53.7 km away")
print("- TOM423 (UK): 69.0 km away")
print("- QTR9U (Qatar): 84.9 km away")